### ISSUE TITLE
Function pyCSM.services.system_service.system_service.get_log_events arguments not working properly.

### ISSUE THREAD

**Issue by twzito** [IBM/pyCSM#16]
The count argument does not limit the number of events created and the session argument does not filter the events returned.

**Comment by blearandy** [comment]
pyCSM was incorrectly processing how to pass down QUERY PARAMs to the REST interface.  This is fixed in https://github.com/IBM/pyCSM/pull/18 which has been pushed to dev on 8/9/22.
