### ISSUE TITLE
Event log times returned by pyCSM.services.system_service.system_service.get_log_events are all the time the function was called.

### ISSUE THREAD

**Issue by twzito** [IBM/pyCSM#17]
All event log entries have the same time, the time that the function was called.  It looks like the created date and event number may also be repeated across multiple entries while the timestamp value does appear to be correct.

                    "createddate": 1660057409749,
                    "eventfilter": "com.ibm.csm.common.events.LogEvent",
                    "eventnumber": 1660057409749,
                    "id": 100321,
                    "inserts": " Backup VM_lbsvm29_CDM_LBSFS5200A",
                    "msgid": "IWNR1026I",
                    "msgtype": 0,
                    "resultText": "IWNR1026I [Aug 9, 2022 8:03:30 AM] The Backup command in the VM_lbsvm29_CDM_LBSFS5200A session completed.",
                    "session": "VM_lbsvm29_CDM_LBSFS5200A",
                    "time": "Tue Aug 09 08:03:29 MST 2022",
                    "timestamp": 1660035605464,
                    "user": "Server"
                },
                {
                    "createddate": 1660057409749,
                    "eventfilter": "com.ibm.csm.common.events.LogEvent",
                    "eventnumber": 1660057409749,
                    "id": 100320,
                    "inserts": " VM_lbsvm29_CDM_LBSFS5200A 2022-08-09 01:59:58 MST 1660035600",
                    "msgid": "IWNR2800I",
                    "msgtype": 0,
                    "resultText": "IWNR2800I [Aug 9, 2022 8:03:30 AM] A recoverable backup of all volumes in session VM_lbsvm29_CDM_LBSFS5200A was created at 2022-08-09 01:59:58 MST with an ID of 1660035600.",
                    "session": "VM_lbsvm29_CDM_LBSFS5200A",
                    "time": "Tue Aug 09 08:03:29 MST 2022",
                    "timestamp": 1660035600001,
                    "user": "Server"
                },
                {
                    "createddate": 1660057409749,
                    "eventfilter": "com.ibm.csm.common.events.LogEvent",
                    "eventnumber": 1660057409749,
                    "id": 100319,
                    "inserts": " Backup VM_lbsvm29_CDM_LBSFS5200A",
                    "msgid": "IWNR1028I",
                    "msgtype": 0,
                    "resultText": "IWNR1028I [Aug 9, 2022 8:03:30 AM] The Backup command in the VM_lbsvm29_CDM_LBSFS5200A session was issued.",
                    "session": "VM_lbsvm29_CDM_LBSFS5200A",
                    "time": "Tue Aug 09 08:03:29 MST 2022",
                    "timestamp": 1660035600002,
                    "user": "Server"
                },
                {
                    "createddate": 1660057409749,
                    "eventfilter": "com.ibm.csm.common.events.LogEvent",
                    "eventnumber": 1660057409749,
                    "id": 100318,
                    "inserts": " Backup VM_lbsvm29_CDM with retention 2 using policy sgc_demo_policy and schedule 1",
                    "msgid": "IWNR2211I",
                    "msgtype": 0,
                    "resultText": "IWNR2211I [Aug 9, 2022 8:03:30 AM] The scheduled task Backup VM_lbsvm29_CDM with retention 2 using policy sgc_demo_policy and schedule 1 has started running.",
                    "session": null,
                    "time": "Tue Aug 09 08:03:29 MST 2022",
                    "timestamp": 1660035600000,
                    "user": "Server"
                },
                {
                    "createddate": 1660057409749,
                    "eventfilter": "com.ibm.csm.common.events.LogEvent",
                    "eventnumber": 1660057409749,
                    "id": 100317,
                    "inserts": " 2022-08-07 01:00:05 MST VM_lbssoar_LBSFS5200A",
                    "msgid": "IWNR2850W",
                    "msgtype": 1,
                    "resultText": "IWNR2850W [Aug 9, 2022 8:03:30 AM] The backup created at 2022-08-07 01:00:05 MST has expired on the hardware for session VM_lbssoar_LBSFS5200A.",
                    "session": "VM_lbssoar_LBSFS5200A",
                    "time": "Tue Aug 09 08:03:29 MST 2022",
                    "timestamp": 1660033795383,
                    "user": "Server"
                },
                {
                    "createddate": 1660057409750,
                    "eventfilter": "com.ibm.csm.common.events.LogEvent",
                    "eventnumber": 1660057409750,
                    "id": 100313,
                    "inserts": " VM_lbssoar_LBSFS5200A 2022-08-09 01:00:00 MST 1660032000",
                    "msgid": "IWNR2800I",
                    "msgtype": 0,
                    "resultText": "IWNR2800I [Aug 9, 2022 8:03:30 AM] A recoverable backup of all volumes in session VM_lbssoar_LBSFS5200A was created at 2022-08-09 01:00:00 MST with an ID of 1660032000.",
                    "session": "VM_lbssoar_LBSFS5200A",
                    "time": "Tue Aug 09 08:03:29 MST 2022",
                    "timestamp": 1660032000002,
                    "user": "Server"
                },
                {
                    "createddate": 1660057409750,
                    "eventfilter": "com.ibm.csm.common.events.LogEvent",
                    "eventnumber": 1660057409750,
                    "id": 100312,
                    "inserts": " Backup VM_lbssoar_LBSFS5200A",
                    "msgid": "IWNR1028I",
                    "msgtype": 0,
                    "resultText": "IWNR1028I [Aug 9, 2022 8:03:30 AM] The Backup command in the VM_lbssoar_LBSFS5200A session was issued.",
                    "session": "VM_lbssoar_LBSFS5200A",
                    "time": "Tue Aug 09 08:03:29 MST 2022",
                    "timestamp": 1660032000003,
                    "user": "Server"
                },

**Comment by blearandy** [comment]
This does not appear to be a pyCSM issue.  This looks to be an issue with what is returned in the REST interface itself.  This will need to be looked at on the CSM product itself.
